exports.countyZh2En = {
  連江縣: 'Lianjiang County',
  臺北市: 'Taipei City',
  新北市: 'New Taipei City',
  基隆市: 'Keelung City',
  桃園市: 'Taoyuan City',
  新竹縣: 'Hsinchu County',
  新竹市: 'Hsinchu City',
  宜蘭縣: 'Ilan County',
  苗栗縣: 'Miaoli County',
  金門縣: 'Kinmen County',
  臺中市: 'Taichung City',
  彰化縣: 'Changhua County',
  花蓮縣: 'Hualien County',
  南投縣: 'Nantou County',
  雲林縣: 'Yunlin County',
  澎湖縣: 'Penghu County',
  嘉義縣: 'Chiayi County',
  嘉義市: 'Chiayi City',
  臺南市: 'Tainan City',
  臺東縣: 'Taitung County',
  高雄市: 'Kaohsiung City',
  屏東縣: 'Pingtung County',
};

exports.countyEn2Zh = {
  'Lianjiang County': '連江縣',
  'Taipei City': '臺北市',
  'New Taipei City': '新北市',
  'Keelung City': '基隆市',
  'Taoyuan City': '桃園市',
  'Hsinchu County': '新竹縣',
  'Hsinchu City': '新竹市',
  'Ilan County': '宜蘭縣',
  'Miaoli County': '苗栗縣',
  'Kinmen County': '金門縣',
  'Taichung City': '臺中市',
  'Changhua County': '彰化縣',
  'Hualien County': '花蓮縣',
  'Nantou County': '南投縣',
  'Yunlin County': '雲林縣',
  'Penghu County': '澎湖縣',
  'Chiayi County': '嘉義縣',
  'Chiayi City': '嘉義市',
  'Tainan City': '臺南市',
  'Taitung County': '臺東縣',
  'Kaohsiung City': '高雄市',
  'Pingtung County': '屏東縣',
};
