const uniq = (a) => {
  const seen = {};
  const out = [];
  const len = a.length;
  let j = 0;
  for (let i = 0; i < len; i += 1) {
    const item = a[i];
    if (seen[item] !== 1) {
      seen[item] = 1;
      out[j++] = item;
    }
  }
  return out;
};

const compare = (a, b) => {
  if (a.TWD97Lat > b.TWD97Lat) {
    return -1;
  }
  if (a.TWD97Lat < b.TWD97Lat) {
    return 1;
  }
  return 0;
};

const locations = [
  {
    SiteName: '臺東',
    SiteEngName: 'Taitung',
    AreaName: '花東空品區',
    County: '臺東縣',
    Township: '臺東市',
    SiteAddress: '臺東市中山路276號',
    TWD97Lon: '121.150450',
    TWD97Lat: '22.755358',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=62&type=l',
  },
  {
    SiteName: '臺南',
    SiteEngName: 'Tainan',
    AreaName: '雲嘉南空品區',
    County: '臺南市',
    Township: '中西區',
    SiteAddress: '臺南市中西區南寧街45號',
    TWD97Lon: '120.202617',
    TWD97Lat: '22.984581',
    SiteType: '一般測站',
  },
  {
    SiteName: '臺西',
    SiteEngName: 'Taixi',
    AreaName: '雲嘉南空品區',
    County: '雲林縣',
    Township: '臺西鄉',
    SiteAddress: '雲林縣臺西鄉五港路505號',
    TWD97Lon: '120.202842',
    TWD97Lat: '23.717533',
    SiteType: '工業測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=41&type=l',
  },
  {
    SiteName: '觀音',
    SiteEngName: 'Guanyin',
    AreaName: '北部空品區',
    County: '桃園市',
    Township: '觀音區',
    SiteAddress: '桃園市觀音區文化路2號',
    TWD97Lon: '121.082761',
    TWD97Lat: '25.035503',
    SiteType: '背景測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=19&type=l',
  },
  {
    SiteName: '關山',
    SiteEngName: 'Guanshan',
    AreaName: '花東空品區',
    County: '臺東縣',
    Township: '關山鎮',
    SiteAddress: '臺東縣關山鎮自強路66號',
    TWD97Lon: '121.161933',
    TWD97Lat: '23.045083',
    SiteType: '其它測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=80&type=l',
  },
  {
    SiteName: '豐原',
    SiteEngName: 'Fengyuan',
    AreaName: '中部空品區',
    County: '臺中市',
    Township: '豐原區',
    SiteAddress: '臺中市豐原區水源路150號',
    TWD97Lon: '120.741711',
    TWD97Lat: '24.256586',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=28&type=l',
  },
  {
    SiteName: '龍潭',
    SiteEngName: 'Longtan',
    AreaName: '北部空品區',
    County: '桃園市',
    Township: '龍潭區',
    SiteAddress: '桃園市龍潭區中正路210號',
    TWD97Lon: '121.216350',
    TWD97Lat: '24.863869',
    SiteType: '一般測站',
  },
  {
    SiteName: '頭份',
    SiteEngName: 'Toufen',
    AreaName: '竹苗空品區',
    County: '苗栗縣',
    Township: '頭份鎮',
    SiteAddress: '苗栗縣頭份鎮文化街20號',
    TWD97Lon: '120.898572',
    TWD97Lat: '24.696969',
    SiteType: '工業測站',
  },
  {
    SiteName: '橋頭',
    SiteEngName: 'Qiaotou',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '橋頭區',
    SiteAddress: '高雄市橋頭區隆豐北路1號',
    TWD97Lon: '120.305689',
    TWD97Lat: '22.757506',
    SiteType: '背景測站',
  },
  {
    SiteName: '線西',
    SiteEngName: 'Xianxi',
    AreaName: '中部空品區',
    County: '彰化縣',
    Township: '線西鄉',
    SiteAddress: '彰化縣線西鄉寓埔村中央路二段145號',
    TWD97Lon: '120.469061',
    TWD97Lat: '24.131672',
    SiteType: '工業測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=34&type=l',
  },
  {
    SiteName: '潮州',
    SiteEngName: 'Chaozhou',
    AreaName: '高屏空品區',
    County: '屏東縣',
    Township: '潮州鎮',
    SiteAddress: '屏東縣潮州鎮九塊里復興路66號',
    TWD97Lon: '120.561175',
    TWD97Lat: '22.523108',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=60&type=l',
  },
  {
    SiteName: '鳳山',
    SiteEngName: 'Fengshan',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '鳳山區',
    SiteAddress: '高雄市鳳山區曹公路6號',
    TWD97Lon: '120.358083',
    TWD97Lat: '22.627392',
    SiteType: '交通測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=50&type=l',
  },
  {
    SiteName: '彰化',
    SiteEngName: 'Changhua',
    AreaName: '中部空品區',
    County: '彰化縣',
    Township: '彰化市',
    SiteAddress: '彰化縣彰化市文心街55號',
    TWD97Lon: '120.541519',
    TWD97Lat: '24.066000',
    SiteType: '一般測站',
  },
  {
    SiteName: '嘉義',
    SiteEngName: 'Chiayi',
    AreaName: '雲嘉南空品區',
    County: '嘉義市',
    Township: '西區',
    SiteAddress: '嘉義市西區新民路580號',
    TWD97Lon: '120.440833',
    TWD97Lat: '23.462778',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=42&type=l',
  },
  {
    SiteName: '萬華',
    SiteEngName: 'Wanhua',
    AreaName: '北部空品區',
    County: '臺北市',
    Township: '萬華區',
    SiteAddress: '臺北市萬華區中華路1段66號',
    TWD97Lon: '121.507972',
    TWD97Lat: '25.046503',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=13&type=l',
  },
  {
    SiteName: '萬里',
    SiteEngName: 'Wanli',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '萬里區',
    SiteAddress: '新北市萬里區瑪鋉路221號',
    TWD97Lon: '121.689881',
    TWD97Lat: '25.179667',
    SiteType: '一般測站',
  },
  {
    SiteName: '楠梓',
    SiteEngName: 'Nanzi',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '楠梓區',
    SiteAddress: '高雄市楠梓區楠梓路262號',
    TWD97Lon: '120.328289',
    TWD97Lat: '22.733667',
    SiteType: '一般測站',
  },
  {
    SiteName: '新營',
    SiteEngName: 'Xinying',
    AreaName: '雲嘉南空品區',
    County: '臺南市',
    Township: '新營區',
    SiteAddress: '臺南市新營區中正路4號',
    TWD97Lon: '120.317250',
    TWD97Lat: '23.305633',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=43&type=l',
  },
  {
    SiteName: '新港',
    SiteEngName: 'Xingang',
    AreaName: '雲嘉南空品區',
    County: '嘉義縣',
    Township: '新港鄉',
    SiteAddress: '嘉義縣新港鄉登雲路105號',
    TWD97Lon: '120.345531',
    TWD97Lat: '23.554839',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=39&type=l',
  },
  {
    SiteName: '新莊',
    SiteEngName: 'Xinzhuang',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '新莊區',
    SiteAddress: '新北市新莊區中正路510號',
    TWD97Lon: '121.432500',
    TWD97Lat: '25.037972',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=7&type=l',
  },
  {
    SiteName: '新店',
    SiteEngName: 'Xindian',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '新店區',
    SiteAddress: '新北市新店區民族路108號',
    TWD97Lon: '121.537778',
    TWD97Lat: '24.977222',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=4&type=l',
  },
  {
    SiteName: '新竹',
    SiteEngName: 'Hsinchu',
    AreaName: '竹苗空品區',
    County: '新竹市',
    Township: '東區',
    SiteAddress: '新竹市民族路33號',
    TWD97Lon: '120.972075',
    TWD97Lat: '24.805619',
    SiteType: '一般測站',
  },
  {
    SiteName: '陽明',
    SiteEngName: 'Yangming',
    AreaName: '北部空品區',
    County: '臺北市',
    Township: '北投區',
    SiteAddress: '臺北市北投區竹子湖路111號',
    TWD97Lon: '121.529583',
    TWD97Lat: '25.182722',
    SiteType: '公園測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=64&type=l',
  },
  {
    SiteName: '菜寮',
    SiteEngName: 'Cailiao',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '三重區',
    SiteAddress: '新北市三重區中正北路163號',
    TWD97Lon: '121.481028',
    TWD97Lat: '25.068950',
    SiteType: '一般測站',
  },
  {
    SiteName: '善化',
    SiteEngName: 'Shanhua',
    AreaName: '雲嘉南空品區',
    County: '臺南市',
    Township: '善化區',
    SiteAddress: '臺南市善化區益名寮60號',
    TWD97Lon: '120.297142',
    TWD97Lat: '23.115097',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=44&type=l',
  },
  {
    SiteName: '湖口',
    SiteEngName: 'Hukou',
    AreaName: '竹苗空品區',
    County: '新竹縣',
    Township: '湖口鄉',
    SiteAddress: '新竹縣湖口鄉成功路360號',
    TWD97Lon: '121.038653',
    TWD97Lat: '24.900142',
    SiteType: '一般測站',
  },
  {
    SiteName: '復興',
    SiteEngName: 'Fuxing',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '前鎮區',
    SiteAddress: '高雄市前鎮區民權二路331號',
    TWD97Lon: '120.312017',
    TWD97Lat: '22.608711',
    SiteType: '交通測站',
  },
  {
    SiteName: '麥寮',
    SiteEngName: 'Mailiao',
    AreaName: '雲嘉南空品區',
    County: '雲林縣',
    Township: '麥寮鄉',
    SiteAddress: '雲林縣麥寮鄉中興路115號',
    TWD97Lon: '120.251825',
    TWD97Lat: '23.753506',
    SiteType: '工業測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=83&type=l',
  },
  {
    SiteName: '淡水',
    SiteEngName: 'Tamsui',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '淡水區',
    SiteAddress: '新北市淡水區中正東路42巷6號',
    TWD97Lon: '121.449239',
    TWD97Lat: '25.164500',
    SiteType: '一般測站',
  },
  {
    SiteName: '崙背',
    SiteEngName: 'Lunbei',
    AreaName: '雲嘉南空品區',
    County: '雲林縣',
    Township: '崙背鄉',
    SiteAddress: '雲林縣崙背鄉南陽村大成路91號',
    TWD97Lon: '120.348742',
    TWD97Lat: '23.757547',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=38&type=l',
  },
  {
    SiteName: '基隆',
    SiteEngName: 'Keelung',
    AreaName: '北部空品區',
    County: '基隆市',
    Township: '信義區',
    SiteAddress: '基隆市東信路324號',
    TWD97Lon: '121.760056',
    TWD97Lat: '25.129167',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=1&type=l',
  },
  {
    SiteName: '馬祖',
    SiteEngName: 'Matsu',
    AreaName: '其他',
    County: '連江縣',
    Township: '南竿鄉',
    SiteAddress: '連江縣南竿鄉介壽村13號',
    TWD97Lon: '119.949875',
    TWD97Lat: '26.160469',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=75&type=l',
  },
  {
    SiteName: '馬公',
    SiteEngName: 'Magong',
    AreaName: '其他',
    County: '澎湖縣',
    Township: '馬公市',
    SiteAddress: '澎湖縣馬公市中正路115號',
    TWD97Lon: '119.566158',
    TWD97Lat: '23.569031',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=78&type=l',
  },
  {
    SiteName: '桃園',
    SiteEngName: 'Taoyuan',
    AreaName: '北部空品區',
    County: '桃園市',
    Township: '桃園區',
    SiteAddress: '桃園市桃園區成功路二段144號',
    TWD97Lon: '121.319964',
    TWD97Lat: '24.994789',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=18&type=l',
  },
  {
    SiteName: '埔里',
    SiteEngName: 'Puli',
    AreaName: '中部空品區',
    County: '南投縣',
    Township: '埔里鎮',
    SiteAddress: '南投縣埔里鎮西安路一段193號',
    TWD97Lon: '120.967903',
    TWD97Lat: '23.968842',
    SiteType: '其它測站',
  },
  {
    SiteName: '苗栗',
    SiteEngName: 'Miaoli',
    AreaName: '竹苗空品區',
    County: '苗栗縣',
    Township: '苗栗市',
    SiteAddress: '苗栗市縣府路100號',
    TWD97Lon: '120.820200',
    TWD97Lat: '24.565269',
    SiteType: '一般測站',
  },
  {
    SiteName: '美濃',
    SiteEngName: 'Meinong',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '美濃區',
    SiteAddress: '高雄市美濃區中壇里忠孝路19號',
    TWD97Lon: '120.530542',
    TWD97Lat: '22.883583',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=47&type=l',
  },
  {
    SiteName: '恆春',
    SiteEngName: 'Hengchun',
    AreaName: '高屏空品區',
    County: '屏東縣',
    Township: '恆春鎮',
    SiteAddress: '屏東縣恆春鎮公園路44號',
    TWD97Lon: '120.788928',
    TWD97Lat: '21.958069',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=61&type=l',
  },
  {
    SiteName: '屏東',
    SiteEngName: 'Pingtung',
    AreaName: '高屏空品區',
    County: '屏東縣',
    Township: '屏東市',
    SiteAddress: '屏東市蘇州街75號',
    TWD97Lon: '120.488033',
    TWD97Lat: '22.673081',
    SiteType: '一般測站',
  },
  {
    SiteName: '南投',
    SiteEngName: 'Nantou',
    AreaName: '中部空品區',
    County: '南投縣',
    Township: '南投市',
    SiteAddress: '南投市南陽路269號',
    TWD97Lon: '120.685306',
    TWD97Lat: '23.913000',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=36&type=l',
  },
  {
    SiteName: '前鎮',
    SiteEngName: 'Qianzhen',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '前鎮區',
    SiteAddress: '高雄市前鎮區中山三路43號',
    TWD97Lon: '120.307564',
    TWD97Lat: '22.605386',
    SiteType: '工業測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=57&type=l',
  },
  {
    SiteName: '前金',
    SiteEngName: 'Qianjin',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '前金區',
    SiteAddress: '高雄市前金區河南二路196號',
    TWD97Lon: '120.288086',
    TWD97Lat: '22.632567',
    SiteType: '一般測站',
  },
  {
    SiteName: '金門',
    SiteEngName: 'Kinmen',
    AreaName: '其他',
    County: '金門縣',
    Township: '金城鎮',
    SiteAddress: '金門縣金城鎮民權路32號',
    TWD97Lon: '118.312256',
    TWD97Lat: '24.432133',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=77&type=l',
  },
  {
    SiteName: '花蓮',
    SiteEngName: 'Hualien',
    AreaName: '花東空品區',
    County: '花蓮縣',
    Township: '花蓮市',
    SiteAddress: '花蓮市中正路210號',
    TWD97Lon: '121.599769',
    TWD97Lat: '23.971306',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=63&type=l',
  },
  {
    SiteName: '松山',
    SiteEngName: 'Songshan',
    AreaName: '北部空品區',
    County: '臺北市',
    Township: '松山區',
    SiteAddress: '臺北市松山區八德路四段746號',
    TWD97Lon: '121.578611',
    TWD97Lat: '25.050000',
    SiteType: '一般測站',
  },
  {
    SiteName: '板橋',
    SiteEngName: 'Banqiao',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '板橋區',
    SiteAddress: '新北市板橋區文化路一段25號',
    TWD97Lon: '121.458667',
    TWD97Lat: '25.012972',
    SiteType: '一般測站',
  },
  {
    SiteName: '林園',
    SiteEngName: 'Linyuan',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '林園區',
    SiteAddress: '高雄市林園區北汕路58巷2號',
    TWD97Lon: '120.411750',
    TWD97Lat: '22.479500',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=52&type=l',
  },
  {
    SiteName: '林口',
    SiteEngName: 'Linkou',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '林口區',
    SiteAddress: '新北市林口區民治路25號',
    TWD97Lon: '121.376869',
    TWD97Lat: '25.077197',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=9&type=l',
  },
  {
    SiteName: '忠明',
    SiteEngName: 'Zhongming',
    AreaName: '中部空品區',
    County: '臺中市',
    Township: '南屯區',
    SiteAddress: '臺中市南屯區公益路二段296號',
    TWD97Lon: '120.641092',
    TWD97Lat: '24.151958',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=31&type=l',
  },
  {
    SiteName: '宜蘭',
    SiteEngName: 'Yilan',
    AreaName: '宜蘭空品區',
    County: '宜蘭縣',
    Township: '宜蘭市',
    SiteAddress: '宜蘭縣宜蘭市復興路二段77號',
    TWD97Lon: '121.746394',
    TWD97Lat: '24.747917',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=65&type=l',
  },
  {
    SiteName: '沙鹿',
    SiteEngName: 'Shalu',
    AreaName: '中部空品區',
    County: '臺中市',
    Township: '沙鹿區',
    SiteAddress: '臺中市沙鹿區英才路150號',
    TWD97Lon: '120.568794',
    TWD97Lat: '24.225628',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=29&type=l',
  },
  {
    SiteName: '西屯',
    SiteEngName: 'Xitun',
    AreaName: '中部空品區',
    County: '臺中市',
    Township: '西屯區',
    SiteAddress: '臺中市西屯區安和路1號',
    TWD97Lon: '120.616917',
    TWD97Lat: '24.162197',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=32&type=l',
  },
  {
    SiteName: '竹東',
    SiteEngName: 'Zhudong',
    AreaName: '竹苗空品區',
    County: '新竹縣',
    Township: '竹東鎮',
    SiteAddress: '新竹縣竹東鎮榮樂里三民街70號',
    TWD97Lon: '121.088903',
    TWD97Lat: '24.740644',
    SiteType: '一般測站',
  },
  {
    SiteName: '竹山',
    SiteEngName: 'Zhushan',
    AreaName: '中部空品區',
    County: '南投縣',
    Township: '竹山鎮',
    SiteAddress: '南投縣竹山鎮大明路666號',
    TWD97Lon: '120.677306',
    TWD97Lat: '23.756389',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=69&type=l',
  },
  {
    SiteName: '汐止',
    SiteEngName: 'Xizhi',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '汐止區',
    SiteAddress: '新北市汐止區樟樹一路141巷2號',
    TWD97Lon: '121.6405878',
    TWD97Lat: '25.0658384',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=2&type=l',
  },
  {
    SiteName: '朴子',
    SiteEngName: 'Puzi',
    AreaName: '雲嘉南空品區',
    County: '嘉義縣',
    Township: '朴子市',
    SiteAddress: '嘉義縣朴子市光復路34號',
    TWD97Lon: '120.247350',
    TWD97Lat: '23.465308',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=40&type=l',
  },
  {
    SiteName: '安南',
    SiteEngName: 'Annan',
    AreaName: '雲嘉南空品區',
    County: '臺南市',
    Township: '安南區',
    SiteAddress: '臺南市安南區安和路三段193號',
    TWD97Lon: '120.217500',
    TWD97Lat: '23.048197',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=45&type=l',
  },
  {
    SiteName: '永和',
    SiteEngName: 'Yonghe',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '永和區',
    SiteAddress: '新北市永和區永和路光復路交口',
    TWD97Lon: '121.516306',
    TWD97Lat: '25.017000',
    SiteType: '交通測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=70&type=l',
  },
  {
    SiteName: '平鎮',
    SiteEngName: 'Pingzhen',
    AreaName: '北部空品區',
    County: '桃園市',
    Township: '平鎮區',
    SiteAddress: '桃園市平鎮區文化街189號',
    TWD97Lon: '121.203986',
    TWD97Lat: '24.952786',
    SiteType: '一般測站',
  },
  {
    SiteName: '左營',
    SiteEngName: 'Zuoying',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '左營區',
    SiteAddress: '高雄市左營區翠華路687號',
    TWD97Lon: '120.292917',
    TWD97Lat: '22.674861',
    SiteType: '一般測站',
  },
  {
    SiteName: '古亭',
    SiteEngName: 'Guting',
    AreaName: '北部空品區',
    County: '臺北市',
    Township: '大安區',
    SiteAddress: '臺北市大安區羅斯福路三段153號',
    TWD97Lon: '121.529556',
    TWD97Lat: '25.020608',
    SiteType: '一般測站',
  },
  {
    SiteName: '冬山',
    SiteEngName: 'Dongshan',
    AreaName: '宜蘭空品區',
    County: '宜蘭縣',
    Township: '冬山鄉',
    SiteAddress: '宜蘭縣冬山鄉南興村照安路26號',
    TWD97Lon: '121.792928',
    TWD97Lat: '24.632203',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=66&type=l',
  },
  {
    SiteName: '斗六',
    SiteEngName: 'Douliu',
    AreaName: '雲嘉南空品區',
    County: '雲林縣',
    Township: '斗六市',
    SiteAddress: '雲林縣斗六市民生路224號',
    TWD97Lon: '120.544994',
    TWD97Lat: '23.711853',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=37&type=l',
  },
  {
    SiteName: '仁武',
    SiteEngName: 'Renwu',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '仁武區',
    SiteAddress: '高雄市仁武區八卦里永仁街555號',
    TWD97Lon: '120.332631',
    TWD97Lat: '22.689056',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=49&type=l',
  },
  {
    SiteName: '中壢',
    SiteEngName: 'Zhongli',
    AreaName: '北部空品區',
    County: '桃園市',
    Township: '中壢區',
    SiteAddress: '桃園市中壢區延平路622號',
    TWD97Lon: '121.221667',
    TWD97Lat: '24.953278',
    SiteType: '交通測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=68&type=l',
  },
  {
    SiteName: '中山',
    SiteEngName: 'Zhongshan',
    AreaName: '北部空品區',
    County: '臺北市',
    Township: '中山區',
    SiteAddress: '臺北市中山區林森北路511號',
    TWD97Lon: '121.526528',
    TWD97Lat: '25.062361',
    SiteType: '一般測站',
  },
  {
    SiteName: '小港',
    SiteEngName: 'Xiaogang',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '小港區',
    SiteAddress: '高雄市小港區平和南路185號',
    TWD97Lon: '120.337736',
    TWD97Lat: '22.565833',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=58&type=l',
  },
  {
    SiteName: '大寮',
    SiteEngName: 'Daliao',
    AreaName: '高屏空品區',
    County: '高雄市',
    Township: '大寮區',
    SiteAddress: '高雄市大寮區潮寮路61號',
    TWD97Lon: '120.425081',
    TWD97Lat: '22.565747',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=51&type=l',
  },
  {
    SiteName: '大園',
    SiteEngName: 'Dayuan',
    AreaName: '北部空品區',
    County: '桃園市',
    Township: '大園區',
    SiteAddress: '桃園市大園區中正東路160號',
    TWD97Lon: '121.201811',
    TWD97Lat: '25.060344',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=18&type=l',
  },
  {
    SiteName: '大里',
    SiteEngName: 'Dali',
    AreaName: '中部空品區',
    County: '臺中市',
    Township: '大里區',
    SiteAddress: '臺中市大里區大新街36號',
    TWD97Lon: '120.677689',
    TWD97Lat: '24.099611',
    SiteType: '一般測站',
  },
  {
    SiteName: '大同',
    SiteEngName: 'Datong',
    AreaName: '北部空品區',
    County: '臺北市',
    Township: '大同區',
    SiteAddress: '臺北市大同區重慶北路三段2號',
    TWD97Lon: '121.513311',
    TWD97Lat: '25.063200',
    SiteType: '交通測站',
  },
  {
    SiteName: '士林',
    SiteEngName: 'Shilin',
    AreaName: '北部空品區',
    County: '臺北市',
    Township: '北投區',
    SiteAddress: '臺北市北投區文林北路155號',
    TWD97Lon: '121.515389',
    TWD97Lat: '25.105417',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=11&type=l',
  },
  {
    SiteName: '土城',
    SiteEngName: 'Tucheng',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '土城區',
    SiteAddress: '新北市土城區學府路一段241號',
    TWD97Lon: '121.451861',
    TWD97Lat: '24.982528',
    SiteType: '一般測站',
  },
  {
    SiteName: '三義',
    SiteEngName: 'Sanyi',
    AreaName: '竹苗空品區',
    County: '苗栗縣',
    Township: '三義鄉',
    SiteAddress: '苗栗縣三義鄉西湖村上湖61-1號',
    TWD97Lon: '120.758833',
    TWD97Lat: '24.382942',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=27&type=l',
  },
  {
    SiteName: '三重',
    SiteEngName: 'Sanchong',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '三重區',
    SiteAddress: '新北市三重區三和路重陽路交口',
    TWD97Lon: '121.493806',
    TWD97Lat: '25.072611',
    SiteType: '交通測站',
  },
  {
    SiteName: '二林',
    SiteEngName: 'Erlin',
    AreaName: '中部空品區',
    County: '彰化縣',
    Township: '二林鎮',
    SiteAddress: '彰化縣二林鎮萬合里江山巷1號',
    TWD97Lon: '120.409653',
    TWD97Lat: '23.925175',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=35&type=l',
  },
  {
    SiteName: '富貴角',
    SiteEngName: 'FugueiCape',
    AreaName: '北部空品區',
    County: '新北市',
    Township: '石門區',
    SiteAddress: '新北市石門區山溪里10鄰九芎林13號',
    TWD97Lon: '121.565258',
    TWD97Lat: '25.263783',
    SiteType: '一般測站',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=84&type=l',
  },
  {
    SiteName: '屏東(琉球)',
    SiteEngName: 'Liuqiu',
    AreaName: '高屏空品區',
    County: '屏東縣',
    Township: '琉球鄉',
    SiteAddress: '929屏東縣琉球鄉中福村行政路12號',
    TWD97Lon: '120.377222',
    TWD97Lat: '22.352222',
    SiteType: '檢測車',
    ImageUrl: 'https://taqm.epa.gov.tw/taqm/webcam.ashx?site=204&type=l',
  },
  {
    SiteName: '苗栗(後龍)',
    SiteEngName: 'Houlong',
    AreaName: '竹苗空品區',
    County: '苗栗縣',
    Township: '後龍鎮',
    SiteAddress: '苗栗縣後龍鎮勝利路',
    TWD97Lon: '120.786028',
    TWD97Lat: '24.616369',
    SiteType: '檢測車',
  },
  {
    SiteName: '桃園(觀音工業區)',
    SiteEngName: 'GuanyinIndustrial',
    AreaName: '北部空品區',
    County: '桃園市',
    Township: '觀音區',
    SiteAddress: '桃園市觀音區新村路二段12號',
    TWD97Lon: '121.128044',
    TWD97Lat: '25.063039',
    SiteType: '工業測站',
  },
  {
    SiteName: '彰化(大城)',
    SiteEngName: 'Dacheng',
    AreaName: '中部空品區',
    County: '彰化縣',
    Township: '大城鄉',
    SiteAddress: '527彰化縣大城鄉 下海漧堤防',
    TWD97Lon: '120.273117',
    TWD97Lat: '23.843139',
    SiteType: '工業測站',
  },
  {
    SiteName: '臺南(麻豆)',
    SiteEngName: 'Madou',
    AreaName: '雲嘉南空品區',
    County: '臺南市',
    Township: '佳里區',
    SiteAddress: '台南市麻豆區和平路9號',
    TWD97Lon: '120.245831',
    TWD97Lat: '23.179047',
    SiteType: '檢測車',
  },
];

const getClosestStation = (lat, long) => {
  let distance = Number.POSITIVE_INFINITY;
  let closestIndex = 40;

  for (i = 0; i < locations.length; i += 1) {
    const squarePlus =
      (lat - locations[i].TWD97Lat) ** 2 + (long - locations[i].TWD97Lon) ** 2;

    if (squarePlus < distance) {
      distance = Math.min(squarePlus, distance);
      closestIndex = i;
    }
  }

  return locations[closestIndex];
};

exports.getClosestStation = getClosestStation;
exports.countys = uniq(locations.sort(compare).map((item) => item.County));
exports.locations = locations;
