platform :ios, '8.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'TWAQI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  #React Pods
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
  ]

  # Pods for TWAQI
  pod 'Firebase/Core'

  # Authentication module for RNFirebase
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'
  pod 'Firebase/Performance'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

end
