# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'TWAQI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TWAQI
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  # Authentication module for RNFirebase
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'
  pod 'Firebase/Performance'

  #React Pods
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'DevSupport'
  ]

end
